### ISSUE TITLE
How do i run this?

### ISSUE THREAD

**Issue by gandie** [SuperKaninchen/hamster-pathfinding#1]
I am very curious to see this working but i need held to get it running.

I downloaded the [Hamster Simulator](http://www.java-hamster-modell.de/download/v29/hamstersimulator-v29-06.zip) thingy and started it:

```bash
~/D/hamstersimulator-v29-06 $ java -jar hamstersimulator.jar
```

Then i moved this repo into the `Programme` folder, created a terrain file with one grain and adjusted PATH as README explains and tried to compile and run. Compiler keeps telling me `Cannot find symbol`, so tried to add `package` statements like documentation found [here](http://www.java-hamster-modell.de/eBooks/hamster2.pdf) says. Still not able to compile and run :crying_cat_face: . Please help.

**Comment by SuperKaninchen** [comment]
Thanks for the report!
Can you please tell me which file and which line causes the error or send a screenshot of the error message?

**Comment by gandie** [comment]
Well, i was able to get arround these errors by compiling all files in the correct order. I suggest you mention this in the README so hamster-noobs like me can play with your toys, too. But i encountered more problems afterwards:

+ I had to alter my `java.policy` file in order to avoid [this exception](https://docs.oracle.com/javase/10/docs/api/java/security/AccessControlException.html) on reading my terrain file. I had help from [these colleagues](https://stackoverflow.com/questions/10454037/java-security-accesscontrolexception-access-denied-java-io-filepermission)
+ After that i ran into `ArrayIndexOutOfBoundsException` in `FileReader`, line 48 - inside the loop building the result array. After starring at your code for a minute or two i switched indexes when assigning result:

```java
if(strings[j] != null) {
	//result[i][j] = strings[j];
	result[j][i] = strings[j];
}
```

Now the hamster is finally running, but i think i broke something because in the end it does not stand on the grain field :laughing:

**Comment by SuperKaninchen** [comment]
Thanks for the reply!
The security exception is caused by the Hamster Simulator. In order to give the Hamster Simulator access to files you have to edit the first line in the `hamster.properties` file and set `security=false`. I will add that part to the README of the repo.
The `ArrayIndexOutOfBoundsException` is a known bug which i‘m currently working to fix asap. I will commit a fix as soon as it‘s ready.

**Comment by SuperKaninchen** [comment]
I just committed the new version which hopefully fixes your problems. If you try it out, please let me know if it worked!

**Comment by gandie** [comment]
Well after pulling latest master, recompiling and running, the hamster still does not reach the korn in the end. Seems like an off-by-one error or something because everything works well until the latest step which seems to always go upwards. This well even cause a `WallInFrontException` if the korn is placed in the first row of terrain.

**Comment by SuperKaninchen** [comment]
I noticed that issue too. I will open a new issue in this repo and refer to this one.

**Comment by gandie** [comment]
As the original problem has been solved this one can be closed now :rocket:
